eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://primary:8761/eureka/,http://secondary:8762/eureka/

sentry:
  dsn: http://b1d24fef2bcd4d4885f5d4777a65d5f8@localhost:9000/4
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  environment: SIT