spring:
  application:
    name: order-svc
server:
  port: 8092

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.137.1:8761/eureka/,http://192.168.137.1:8762/eureka/