apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris-app
  labels:
    app: polaris-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polaris-app
  template:
    metadata:
      labels:
        app: polaris-app
    spec:
      containers:
        - name: polaris-app
          image: polaris952/polaris-app:latest
          ports:
            - containerPort: 8090