spring:
  application:
    name: service-registration-center
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1

---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
