spring:
  application:
    name: service-registration-center
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: primary

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://secondary:8762/eureka/

---
spring:
  profiles: secondary

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://primary:8761/eureka/
